# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MRoelandts
masthead_title: "Welcome to mroelandts"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Home page for whatever I want on the internet. Mostly used for testing
  but it can also turn into a blog or a protfolio or something.
github_username: mroelandts
minimal_mistakes_skin: default
search: false
#locale: "nl-BE"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate_path: /page:num/
timezone: BE # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Matthias Roelandts"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "A motivated person that wants to learn all what technology has to offer!"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mroelandts"
    - label: "Stackoverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/4372256/matthiasroelandts"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mroelandts"
    - label: "Stackoverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/4372256/matthiasroelandts"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/matthias.roelandts.1"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCe1CcDMumN3CarckgJC8xXw"


defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
